<?php

class BannerBlock_Controller extends Controller
{
	public function Main($args = false)
	{
	    //$this->sectionAlias = 'home';
	    
        //можно и здесь указать фильтры (здесь приоритет выше)
        /*
        $args['filter'] = array(
            'groups' => array('name' => 'Баннеры', 'id' => array(1,2,3,4,5)),
            'collections' => array('id' => array(9,10)),
        );
        */
	    
	    
		parent::Main($args); // TODO: Change the autogenerated stub
	}
}
