<?php

class ModuleTest_Controller extends Controller
{
	public function Main($args = false)
	{
		parent::Main($args); // TODO: Change the autogenerated stub
	}
	
	public function Handler()
	{
	    
	    $response = array();
	    
	    $name = trim($_REQUEST['name']);
	    
	    if($name) {
	        $response['name'] = $name;
	        echo json_encode($response);
	    }
	    
	}
	
}
