<?php

class TextBlock_Controller extends Controller
{
	public function Main($args = false)
	{
		parent::Main($args); // TODO: Change the autogenerated stub
	}

	public function Item($args = false)
	{
		parent::Item($args); // TODO: Change the autogenerated stub
	}
}
